PHP 8.2 with dependencies
spryker/docker-php pull request #70
Opened 2023-04-25 10:04 UTC by kalaputsik

## PR Description
Ticket - https://spryker.atlassian.net/browse/SC-13160

Changelog:
- PHP 8.2
- Blackfire: 1.86.4
- Tideways: 5.5.14
- NewRelic: 10.9.0.324
- Composer: 2.5.5

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2023-04-25 10:55 UTC, zyuzka requested changes
What about other Alpine versions?

2023-04-25 10:55 UTC, zyuzka commented on alpine/3.16/8.2/Dockerfile
> +ARG COMPOSER_VERSION=2.5.5
If it's possible - we should update versions into all our images

2023-04-25 10:55 UTC, zyuzka commented on alpine/3.16/8.2/Dockerfile
> +RUN apk update \
Please add next line:
`&& apk upgrade \`

2023-04-25 10:55 UTC, zyuzka commented on debian/bullseye/8.2/Dockerfile
> +    golang-go \
I have a suggestion about Go in Debian. Please wait for my PR with vulnerability issues fixes

2023-04-26 08:37 UTC, alexanderM91 commented
Hi @kalaputsik, could you please remove Alpine 3.14 from our list as Alpine 3.14 will be deprecated in 6 days?

2023-04-27 19:42 UTC, zyuzka requested changes

2023-05-08 12:22 UTC, alexanderM91 approved these changes

2023-05-09 07:11 UTC, merged