FRW-8801 Added PHP 8.3 support.
spryker/docker-php pull request #99
Opened 2024-09-06 12:10 UTC by olhalivitchuk

## PR Description
Tickets: 
- https://spryker.atlassian.net/browse/FRW-8801

## Relation:
- https://github.com/spryker/suite-nonsplit/pull/9017

## Changelog:
- Added support for PHP 8.3

## Checklist
- [x] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2024-09-10 07:16 UTC, alexanderM91 requested changes

2024-09-10 09:17 UTC, olhalivitchuk commented on .github/workflows/ci.yml
> +            tags: [ "spryker/php:8.2", "spryker/php:8.2-alpine3.18" ]
Yes, it was agreed with @gechetspr

2024-09-16 09:37 UTC, alexanderM91 commented on README.md
> +| Tag                                                                                         | PHP version | Linux distribution | Details
Please remove .DS_Store file from the PR.

2024-09-16 09:42 UTC, alexanderM91 approved these changes

2024-09-16 14:25 UTC, alexanderM91 approved these changes

2024-09-16 19:52 UTC, merged